name: Issue Handler

on: 
  issues:
    types: [opened, reopened]

jobs:
  handle-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print Issue Information
      env:
       ISSUE_NUMBER: ${{ github.event.issue.number }}
       ISSUE_TITLE: ${{ github.event.issue.title }}
       ISSUE_BODY: ${{ github.event.issue.body }}
       ISSUE_ASSIGNEES: $(echo ${{ join(github.event.issue.assignees.*.login, ', ') }})
       ISSUE_LABELS: $(echo ${{ join(github.event.issue.labels.*.name, ', ') }})
      run: |
          echo "Issue Number: ${ISSUE_NUMBER}"
          echo "Issue Body: ${ISSUE_BODY}"
          echo "Issue Assignees: ${ISSUE_ASSIGNEES}"
          echo "Issue Labels: ${ISSUE_LABELS}"
